### PR TITLE
Change the approach of TryDecorateDescriptors method

### PR DESCRIPTION
**Pull request by mjebrahimi**
Change ServiceType of Decorated service instead of removing it when registering Decorator service
In order to previous #79  PR [comment ](https://github.com/khellang/Scrutor/pull/79#issuecomment-461406709)

### CODE REVIEW

**Comment by khellang** [comment]
How does this relate to https://github.com/khellang/Scrutor/pull/78? I think this might be going a bit too far, adding a *ton* of API surface area in the process.

**Comment by mjebrahimi** [comment]
You were very fast
I was writing the previous PR comment 😝

**Comment by khellang** [comment]
Sorry for taking so long to respond 😞 I'm worried by the amount of added code and complexity here. It's almost to the point where I'm getting lost in overloads and code flow.

This library was never meant to be a full replacement for other feature-rich containers that support these kinds of complex scenarios. I still think the recommendation to use a 3rd party container is valid when Scrutor falls short. I'm thinking this might be the case this time, as I'm not sure I can see myself maintaining this code 😢

Do you think there is way this could be shipped without merging it into Scrutor, as a separate package or something?

**Comment by khellang** [comment]
I'm closing this as I can't see myself taking on this amount of code in the foreseeable future 😅

**Pull request closed without merging**
