### PR TITLE
- Upgrade from Beta 8 -> RC 1

### PR DESCRIPTION
**Pull request by SharpNoiZy**
Everything functional, except one UnitTest fails, but I don't know why exactly.

### CODE REVIEW

**Comment by khellang** [comment]
Ah, I was planning to do a bit of work on this tonight. Thanks for beating me to it! :+1:

Unfortunately, all spaces have been converted to tabs, which makes this PR very hard to review. Would you be able to change them back? :innocent:

**Comment by SharpNoiZy** [comment]
Tabs are much better than spaces, each developer can decide in his IDE how long they want to display a tab! ;)

But it's really easy, I just changed the version number, upgrade all dependencies and replace the old Beta 8 DI namespace with the new RC1 DI namespace.
That's it.

Kind regards

**Comment by khellang** [comment]
OK, let's not get into a holy war about tabs vs. spaces :wink: This repo uses spaces - period.

I'd :heart: to take your contribution, but not in its current state. Feel free to convert back to spaces and reopen this PR :smile:

**Comment by SharpNoiZy** [comment]
I don't know how to convert them back to spaces.

**Comment by gep13** [comment]
@khellang would adding an EditorConfig file to the root of your project help with this happening in the future?  Granted, that relies on a person having the EditorConfig extension installed in their IDE/Editor of choice, but at least your preferences for your repository are declared.

**Comment by khellang** [comment]
@SharpNoiZy How did you convert things to tabs in the first place? :stuck_out_tongue: 

@gep13 Yes, but since this repo is pretty fresh, I haven't had the time to add it yet. I was planning on working on this tonight, adding .editorconfig, .DotSettings and setting up AppVeyor :smile:

**Comment by gep13** [comment]
>@khellang said...
@gep13 Yes, but since this repo is pretty fresh, I haven't had the time to add it yet. I was planning on working on this tonight, adding .editorconfig, .DotSettings and setting up AppVeyor :smile:

Ah gotcha! :+1:

**Pull request closed without merging**
