### PR TITLE
Tests lifetime for decorator

### PR DESCRIPTION
**Pull request by mjebrahimi**
I added tests for checking lifetime of DecorateSingleton, DecorateScoped, DecorateTransient and checking lifetime of decorator and decoratee is the same

### CODE REVIEW

**Comment by khellang** [comment]
Could you add some tests that actually resolves and disposes some services to make sure the lifetimes are still correct?

I'm worried that, using this method, if you register a scoped service and decorate it with a transient decorator, the scoped service actually ends up being transient.

**Comment by khellang** [comment]
This test fails:

```csharp
[Fact]
public void DisposableServicesWithDifferentLifetimesAreDisposed()
{
    var provider = ConfigureProvider(services =>
    {
        services.AddScoped<IDisposableService, DisposableService>();

        services.DecorateTransient<IDisposableService, DisposableServiceDecorator>();
    });

    var disposable1 = provider.GetRequiredService<IDisposableService>();
    var disposable2 = provider.GetRequiredService<IDisposableService>();

    var decorator1 = Assert.IsType<DisposableServiceDecorator>(disposable1);
    var decorator2 = Assert.IsType<DisposableServiceDecorator>(disposable2);

    Assert.Same(decorator1.Inner, decorator2.Inner);

    provider.Dispose();

    Assert.True(decorator1.WasDisposed);
    Assert.True(decorator2.Inner.WasDisposed);

    Assert.True(decorator1.WasDisposed);
    Assert.True(decorator2.Inner.WasDisposed);
}
```

```
Assert.Same() Failure
Expected: DisposableService { WasDisposed = False }
Actual:   DisposableService { WasDisposed = False }
   at Scrutor.Tests.DecorationTests.DisposableServicesWithDifferentLifetimesAreDisposed()
```

This is what I was trying to say in https://github.com/khellang/Scrutor/issues/38#issuecomment-344749130:

> We don't "clone" anything. We literally replace the decoratee with the decorator in the service collection. Which means there's no way to have a decorator and a decoratee with different lifetimes.

When you register `DisposableService` as scoped, you expect the same instance to be resolved within the same scope. Since we replace the existing descriptor with the decorated one, we effectively replace the lifetime of the existing registration with the lifetime of the descriptor. That's really problematic.

**Comment by mjebrahimi** [comment]
Oh shit
The problem is bigger than that.

After the reviews and debug that I did, I came to the conclusion.
According to the ActivatorUtilities class source, the [GetServiceOrCreateInstance](https://github.com/aspnet/Extensions/blob/980cd8d947331110bd124201e777521dc594346d/src/Shared/src/ActivatorUtilities/ActivatorUtilities.cs#L148) method tries to resolve a type from ServiceProvider that is already registered. If not, it instantiates the type using reflection.

Since the Decorated service [gets removed](https://github.com/khellang/Scrutor/blob/195006f35cc958ef26af050c5ad7b88ec3f5cfdb/src/Scrutor/ServiceCollectionExtensions.Decoration.cs#L288) from the ServiceCollection services, therefore the Decorated service isn't get resolved from ServiceProvider within ActivatorUtilities.GetServiceOrCreateInstance method and it cause your above test fails because a new instance of Decorated service will be made by Reflection every time.

In fact, **we should not remove Decorated service from the ServiceCollection services as third-party IOC containers (like Autofac) do.**
But if we do not remove it, both Decorated and Decorator will be registered by the same ServiceType, which cause our Decorator to get into trouble.

Therefore, when registering the Decorator, **we've to change ServiceType of the Decorated service instead of removing it.** 
This will make our Decorator work correctly and resolve the Decorated service from ServiceProvider.
So the above test will not fail and everything will works fine and I think it's basically the right way.

Another problem that the way used now in Scrutor is that **Decorated services are not disposed automatically because they have not been resolved by serviceProvider and they're made by Reflection** within ActivatorUtilities.GetServiceOrCreateInstance.

Basically, ServiceProvider disposes all instances it provides that have IDisposable implementation too at the right time. (for example, all transient and scoped services will be disposed at end of http request due to the end of Scope life)

But now, if the Decorator service doesn't dispose the Decorated service, the **Decorated service will never gets disposed** because it is not created and managed by ServiceProvider. (And it can be very problematic!)

Finally I modified the code a bit and fixed the problem and all the tests are passed.
I used Reflection.Emit to change ServiceType of Decorated service descriptor when registering Decorator service (In summary I've added a random Guid after the ServiceType's name of Decorated service. For example "DecoratedService_XXX..".
And when retrieving the Decorator service, I'll resolve Decorated service from ServiceProvider and pass it into the Decorator constructor.

I'll send you [the PR](https://github.com/khellang/Scrutor/pull/80) so you can review it.
Thanks in advance.

**Comment by mjebrahimi** [comment]
Ping!

**Comment by khellang** [comment]
Superseded by #80

**Pull request closed without merging**
